/**
 * There are many types of transaction.
 */

public enum TransactionType {
    TRANSFER_OUT, TRANSFER_IN, LOAN, SAVE, WITHDRAW, BALANCE_REMAINED_WHEN_CLOSE, OPEN_ACCOUNT_FEE, CLOSE_ACCOUNT_FEE, WITHDRAW_FEE, TRANSFER_FEE, LOAN_INTEREST, SAVE_INTEREST, LOAN_REPAY
}
